In [2]:
#Kütüphaneler
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt

In [3]:
#Veriyi çekiyoruz
Data1=pd.read_csv("veriler.csv",delimiter=";")

In [4]:
Data1

ulke    boy   kilo   yas cinsiyet
0    tr  130.0   30.0  10.0        e
1    tr  125.0   36.0  11.0        e
2    tr  135.0   34.0  10.0        k
3    tr  133.0   30.0   9.0        k
4    tr  180.0   38.0  12.0        e
5    tr  190.0   90.0  30.0        e
6    tr  175.0   80.0  25.0        e
7    tr  177.0   90.0  35.0        e
8    tr  185.0   60.0  22.0        k
9    us  165.0  105.0  33.0        e
10   us  155.0   55.0  27.0        k
11   us  160.0   50.0  44.0        k
12   us  162.0   58.0  39.0        k
13   us  167.0   59.0  41.0        k
14   us  174.0   62.0  55.0        k
15   fr  193.0   70.0  47.0        e
16   fr  187.0   90.0  28.0        e
17   fr  183.0   80.0  29.0        e
18   fr  159.0   88.0  32.0        e
19   fr  164.0   40.0  42.0        k
20   fr  166.0   66.0  51.0        k
21   fr  166.0   56.0  62.0        k
22  NaN    NaN    NaN   NaN      NaN

In [5]:
Data1.drop([22],axis=0,inplace=True)

In [6]:
#Ogrenecek kolonlari ve sonuc elde edeceğimiz kolonu ayiriyoruz
x=Data1.iloc[:,1:4].values
y=Data1.iloc[:,4:].values

In [7]:
#Verileri train ve Test verileri olarak ayırıyoruz...
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

In [9]:
#Datayi 0 ile 1 arasında küçültüyoruz
from sklearn.preprocessing import StandardScaler

In [10]:
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [11]:
#Logistic regresyon ile verileri eğitiyoruz ve tahmin etiriyoruz
from sklearn.linear_model import LogisticRegression

In [12]:
logistic=LogisticRegression(random_state=0)
logistic.fit(X_train,y_train)
Tahmin=logistic.predict(X_test)
print(Tahmin)
y_test

['e' 'e' 'e' 'e' 'k' 'e' 'e' 'k']


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


array([['k'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['k'],
       ['k'],
       ['k']], dtype=object)

In [ ]:
#Sonuclar çok kötü bunun sebebi küçük yaştaki kişiler makinenin aklını karıştırıyor.
#Kücük yastakileri kaldiriyoruz..

In [13]:

Data1.drop([0,1,2,3,4],axis=0,inplace=True)
x=Data1.iloc[:,1:4].values
y=Data1.iloc[:,4:].values

In [14]:
#Datayı test ve train data olarak ikiye ayiriyoruz
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=0)

In [15]:
#Verileri 0 ile 1 arasında kücültüyoruz
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)
logistic.fit(X_train,y_train)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(random_state=0)

In [16]:
#Logistic Regresyonla verileri tahmin ediyoruz
Tahmin=logistic.predict(X_test)
print(Tahmin)
y_test

['e' 'k' 'k' 'k' 'k' 'e']


array([['e'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e']], dtype=object)

In [ ]:
#Simdi daha iyi sonuc vermeye basladi...

In [17]:
from sklearn.metrics import confusion_matrix

In [18]:
cm=confusion_matrix(Tahmin,y_test)

In [19]:
cm

array([[2, 0],
       [1, 3]], dtype=int64)

In [ ]:
#Daha iyi sonuçlar almak için diğer modeleri deniyoruz...

In [20]:
#KNN Model
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=10,metric="minkowski")
kn.fit(X_train,y_train)
KNtahmin=kn.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [21]:
confusion_matrix(y_test,KNtahmin)

array([[3, 0],
       [1, 2]], dtype=int64)

In [22]:
#SVC Model
from sklearn.svm import SVC
svc=SVC(kernel="poly")
svc.fit(X_train,y_train)
Tahmin=svc.predict(X_test)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [23]:
confusion_matrix(y_test,Tahmin)

array([[2, 1],
       [1, 2]], dtype=int64)

In [24]:
from sklearn.naive_bayes import GaussianNB

In [25]:
nb=GaussianNB()
nb.fit(X_train,y_train)
Tahmin=nb.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [26]:
confusion_matrix(y_test,Tahmin)

array([[2, 1],
       [0, 3]], dtype=int64)

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
#Desicion Tree(Karar agacı)
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy")
dtc.fit(X_train,y_train)
Tahmin=dtc.predict(X_test)
confusion_matrix(y_test,Tahmin)

array([[3, 0],
       [0, 3]], dtype=int64)

In [29]:
print("Decision Tree (Karar agacı)")
confusion_matrix(y_test,Tahmin)

Decision Tree (Karar agacı)


array([[3, 0],
       [0, 3]], dtype=int64)

In [31]:
#rassal orman sınıflandırılması
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=4,criterion="entropy")
rfc.fit(X_train,y_train)
Tahmin=rfc.predict(X_test)
confusion_matrix(y_test,Tahmin)

C:\Users\SEFASZ~1\AppData\Local\Temp/ipykernel_26192/1559776187.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(X_train,y_train)


array([[2, 1],
       [1, 2]], dtype=int64)

#ROC,TPR,FPR

In [35]:
from sklearn import metrics

In [45]:
y_proba=rfc.predict_proba(X_test)
fpr,tpr,thold=metrics.roc_curve(y_test,y_proba[:,0],pos_label="e")


In [46]:
fpr

array([0.        , 0.        , 0.        , 0.33333333, 1.        ])

In [47]:
tpr

array([0.        , 0.66666667, 1.        , 1.        , 1.        ])

In [48]:
thold

array([1.75, 0.75, 0.5 , 0.25, 0.  ])

In [49]:
y_test

array([['e'],
       ['k'],
       ['k'],
       ['k'],
       ['e'],
       ['e']], dtype=object)

In [51]:
y_proba

array([[0.5 , 0.5 ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.25, 0.75],
       [0.75, 0.25],
       [0.75, 0.25]])