In [1]:
#Kütüphaneler
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Veriyi çekiyoruz
Data1=pd.read_excel("derin.xlsx")
Data1

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2         0              1          1               1   
1          1   8380786              1          0               1   
2          8   1596608              3          1               0   
3          1         0              2          0               0   
4          2  12551082              1          1               1   
...      ...       ...            ...        ...             ...   
9995       5         0              2          1               0   
9996      10   5736961              1          1               1   
9997       7         0              1          0               1   
9998       3   7507531              2          1               0   
9999       4  13014279              1          1               0   

      EstimatedSalary  Exited  
0            10134888       1  
1            11254258       0  
2            11393157       1  
3             9382663       0  
4              790841       0  
...               ...     ...  
9995          9627064       0  
9996         10169977       0  
9997          4208558       1  
9998          9288852       1  
9999          3819078       0  

[10000 rows x 14 columns]

In [ ]:
#Öğrenecek kolonları ve sonuç kolonlarini ayiriyoruz.
X=Data1.iloc[:,3:13].values
Y=Data1.iloc[:,13].values

In [4]:
#Katagorikten Numaric e götürüyoruz
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [5]:
le1=preprocessing.LabelEncoder()
X[:,1]=le1.fit_transform(X[:,1])
le2=preprocessing.LabelEncoder()
X[:,2]=le2.fit_transform(X[:,2])

In [6]:
ohe=ColumnTransformer([("ohe",OneHotEncoder(dtype=float),[1])],remainder="passthrough")

In [7]:
X=ohe.fit_transform(X)

In [8]:
X[0:1]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0, 1, 1, 1, 10134888]], dtype=object)

In [9]:
#Verileri train ve test datası olarak ayırıyoruz.
from sklearn.model_selection import train_test_split 

In [10]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=0)

In [11]:
#Verileri 0 ile 1 arasında skaler ediyoruz
from sklearn.preprocessing import StandardScaler

In [12]:
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

In [13]:
#Model inşaası
import keras
from keras.models import Sequential
from keras.layers import Dense

In [14]:
Classifier=Sequential()
Classifier.add(Dense(6,activation="relu"))
Classifier.add(Dense(6,activation="relu"))
Classifier.add(Dense(1,activation="sigmoid"))
Classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics="accuracy")
Classifier.fit(X_train,y_train,epochs=300)
y_pred=Classifier.predict(X_test)

Epoch 1/300
210/210 [==============================] - 1s 748us/step - loss: 0.5323 - accuracy: 0.7979
Epoch 2/300
210/210 [==============================] - 0s 777us/step - loss: 0.4792 - accuracy: 0.7979
Epoch 3/300
210/210 [==============================] - 0s 631us/step - loss: 0.4484 - accuracy: 0.7991
Epoch 4/300
210/210 [==============================] - 0s 660us/step - loss: 0.4335 - accuracy: 0.8087
Epoch 5/300
210/210 [==============================] - 0s 657us/step - loss: 0.4266 - accuracy: 0.8099
Epoch 6/300
210/210 [==============================] - 0s 676us/step - loss: 0.4213 - accuracy: 0.8124
Epoch 7/300
210/210 [==============================] - 0s 660us/step - loss: 0.4166 - accuracy: 0.8146
Epoch 8/300
210/210 [==============================] - 0s 657us/step - loss: 0.4119 - accuracy: 0.8169
Epoch 9/300
210/210 [==============================] - 0s 676us/step - loss: 0.4076 - accuracy: 0.8191
Epoch 10/300
210/210 [==============================] - 0s 1ms/step - los

210/210 [==============================] - 0s 679us/step - loss: 0.3307 - accuracy: 0.8661
Epoch 160/300
210/210 [==============================] - 0s 662us/step - loss: 0.3303 - accuracy: 0.8669
Epoch 161/300
210/210 [==============================] - 0s 656us/step - loss: 0.3304 - accuracy: 0.8670
Epoch 162/300
210/210 [==============================] - 0s 705us/step - loss: 0.3305 - accuracy: 0.8675
Epoch 163/300
210/210 [==============================] - 0s 689us/step - loss: 0.3306 - accuracy: 0.8682
Epoch 164/300
210/210 [==============================] - 0s 651us/step - loss: 0.3301 - accuracy: 0.8666
Epoch 165/300
210/210 [==============================] - 0s 689us/step - loss: 0.3303 - accuracy: 0.8663
Epoch 166/300
210/210 [==============================] - 0s 651us/step - loss: 0.3302 - accuracy: 0.8682
Epoch 167/300
210/210 [==============================] - 0s 638us/step - loss: 0.3299 - accuracy: 0.8685
Epoch 168/300
210/210 [==============================] - 0s 654us/ste

In [15]:
#Sonucları confusion matrix ile kontrol ediyoruz
from sklearn.metrics import confusion_matrix
y_pred=(y_pred>0.5)
cm=confusion_matrix(y_test,y_pred)

In [16]:
cm

array([[2522,   95],
       [ 382,  301]], dtype=int64)

In [17]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [18]:
y_test

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [19]:
#XGBoost Modeli
from xgboost import XGBClassifier
xgbc=XGBClassifier()


In [21]:
xgbc.fit(X_train,y_train)
Tahmin=xgbc.predict(X_test)
cm=confusion_matrix(Tahmin,y_test)

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:20:38] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [24]:
cm

array([[2469,  331],
       [ 148,  352]], dtype=int64)

In [25]:
#k-katlamali capraz sorgulama
from sklearn.model_selection import cross_val_score
basari=cross_val_score(estimator=xgbc,X=X_train,y=y_train,cv=4)
basari.mean()

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:22:36] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:22:37] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:22:37] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[12:22:37] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


0.8534328358208955