In [1]:
#kütüphaneler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Verileri çekiyoruz
Data1=pd.read_excel("maaslar_yeni.xlsx")

In [3]:
Data1

Calisan ID             unvan  UnvanSeviyesi  Kidem  Puan   maas
0            1             Cayci              1      5    70   2250
1            2          Sekreter              2      5    70   2500
2            3  Uzman Yardimcisi              3      5    70   3000
3            4             Uzman              4      5    70   4000
4            5  Proje Yoneticisi              5      5    70   5500
5            6               Sef              6      5    70   7500
6            7             Mudur              7      5    70  10000
7            8          Direktor              8      5    70  15000
8            9           C-level              9      5    70  25000
9           10               CEO             10      5    70  50000
10          11             Cayci              1      7    99   2000
11          12          Sekreter              2      7     9   2500
12          13  Uzman Yardimcisi              3      7    62   4000
13          14             Uzman              4      4    38   3000
14          15  Proje Yoneticisi              5      1    80   5000
15          16               Sef              6      2    35   5000
16          17             Mudur              7      8    99  12000
17          18          Direktor              8      4    58  11000
18          19           C-level              9      2    20  15000
19          20               CEO             10      4    42  22000
20          21             Cayci              1      8    11   2200
21          22          Sekreter              2      2    53   2200
22          23  Uzman Yardimcisi              3      8    50   2800
23          24             Uzman              4      9    91   6000
24          25  Proje Yoneticisi              5      9    71   5400
25          26               Sef              6      1     2   4000
26          27             Mudur              7     10    81  12000
27          28          Direktor              8     10    38  10000
28          29           C-level              9      1    50  15000
29          30               CEO             10      9    83  60000

In [4]:
#Datayı öğrenilecek kolonlar ve sonuc kolonunu ayiriyoruz
X=Data1.iloc[:,2:5].values
Y=Data1.iloc[:,5].values
Hepsi=Data1.iloc[:,2:6]

In [5]:
#Makinenin daha iyi ögrenmesi için verileri eliyerek en iyisini buluyoruz
import statsmodels.api as ms

In [12]:
X=np.append(arr=np.ones((30,1)).astype(int),values=Hepsi,axis=1)
X_l=Hepsi.iloc[:,[0]].values
X_l=np.array(X_l,dtype=float)
model=ms.OLS(Y,X_l).fit()

In [13]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.676
Model:                            OLS   Adj. R-squared (uncentered):              0.665
Method:                 Least Squares   F-statistic:                              60.59
Date:                Mon, 07 Mar 2022   Prob (F-statistic):                    1.39e-08
Time:                        01:55:33   Log-Likelihood:                         -318.10
No. Observations:                  30   AIC:                                      638.2
Df Residuals:                      29   BIC:                                      639.6
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          2269.9134    291.626      7.784      0.000    1673.472    2866.355
==============================================================================
Omnibus:                       42.594   Durbin-Watson:                   1.175
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              142.872
Skew:                           3.058   Prob(JB):                     9.46e-32
Kurtosis:                      11.768   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [31]:
train=Hepsi.iloc[:,0:3].values

In [32]:
train

array([[ 1,  5, 70],
       [ 2,  5, 70],
       [ 3,  5, 70],
       [ 4,  5, 70],
       [ 5,  5, 70],
       [ 6,  5, 70],
       [ 7,  5, 70],
       [ 8,  5, 70],
       [ 9,  5, 70],
       [10,  5, 70],
       [ 1,  7, 99],
       [ 2,  7,  9],
       [ 3,  7, 62],
       [ 4,  4, 38],
       [ 5,  1, 80],
       [ 6,  2, 35],
       [ 7,  8, 99],
       [ 8,  4, 58],
       [ 9,  2, 20],
       [10,  4, 42],
       [ 1,  8, 11],
       [ 2,  2, 53],
       [ 3,  8, 50],
       [ 4,  9, 91],
       [ 5,  9, 71],
       [ 6,  1,  2],
       [ 7, 10, 81],
       [ 8, 10, 38],
       [ 9,  1, 50],
       [10,  9, 83]], dtype=int64)

In [33]:
#Verileri train verileri ve test verileri olarak ayiriyoruz
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test=train_test_split(train,Y,test_size=0.20,random_state=0)

In [35]:
y_train

array([10000,  2500, 11000,  2800,  7500, 12000, 25000,  5000,  6000,
        2200,  2500, 60000, 10000,  5500, 15000, 22000, 50000, 15000,
        4000,  4000,  2250,  2200,  5000,  4000], dtype=int64)

In [48]:
#linear 
from sklearn.linear_model import LinearRegression

In [49]:
lin_reg=LinearRegression()
lin_reg.fit(x_train,y_train)
lin_reg.predict(x_test)

array([ 2746.95120021, 18232.52805531,  3072.51397169,  -157.82197644,
       24056.49623584, 14954.81791349])

In [50]:
#poly
from sklearn.preprocessing import PolynomialFeatures

In [51]:
lin_poly=PolynomialFeatures(degree=4)
Xpoly=lin_poly.fit_transform(x_train)
lin_reg2=LinearRegression()
lin_reg2.fit(Xpoly,y_train)
lin_reg2.predict(lin_poly.fit_transform(x_test))

array([  2881.48524924,  24173.42802073,  19679.38774839, 161904.07199495,
       -55124.65796391, -38899.74112773])

In [52]:
#SVR("rbf")
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

In [77]:
x_scaler=StandardScaler().fit_transform(x_train)
x_tescaler=StandardScaler().fit_transform(x_test)
svr=SVR(kernel="rbf")
svr.fit(x_scaler,y_train)
svr.predict(StandardScaler().fit_transform(x_test))

array([5746.84591807, 5751.41708245, 5748.08898826, 5748.01180442,
       5753.45485138, 5750.97439184])

In [68]:
#tree
from sklearn.tree import DecisionTreeRegressor

In [69]:
tree=DecisionTreeRegressor(random_state=0)
tree.fit(x_train,y_train)
tree.predict(x_test)

array([ 4000., 15000.,  4000.,  2250., 10000.,  5500.])

In [70]:
#rassal
from sklearn.ensemble import RandomForestRegressor

In [71]:
rassal=RandomForestRegressor(n_estimators=40,random_state=0)
rassal.fit(x_train,y_train)
rassal.predict(x_test)

array([ 3683.75, 16975.  ,  4332.5 ,  2546.25, 11575.  ,  7020.  ])

In [72]:
#r2 score ile kontrol ediyoruz
from sklearn.metrics import r2_score

In [73]:
print("Linear kontrol")
r2_score(y_test,lin_reg.predict(x_test))

Linear kontrol


-0.7000115130043334

In [74]:
print("poly kontrol")
r2_score(y_test,lin_reg2.predict(lin_poly.fit_transform(x_test)))

poly kontrol


-217.72097309437473

In [79]:
print("svr kontrol")
r2_score(y_test,svr.predict(x_test))

svr kontrol


-0.03918654653208398

In [80]:
print("tree kontrol")
r2_score(y_test,tree.predict(x_test))

tree kontrol


0.9590065256525653

In [81]:
print("rassal kontrol")
r2_score(y_test,rassal.predict(x_test))

rassal kontrol


0.9375757692956795

In [82]:
x_test

array([[ 3,  5, 70],
       [ 9,  1, 50],
       [ 4,  4, 38],
       [ 1,  7, 99],
       [ 7, 10, 81],
       [ 5,  9, 71]], dtype=int64)