In [1]:
#Kütüphaneler
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Veriyi çekiyoruz
Data1=pd.read_excel("wine.xlsx")

In [3]:
Data1

Alcohol  Malic_Acid  Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0       1423         171  243           156        127             28   
1        132         178  214           112        100            265   
2       1316         236  267           186        101             28   
3       1437         195   25           168        113            385   
4       1324         259  287            21        118             28   
..       ...         ...  ...           ...        ...            ...   
173     1371         565  245           205         95            168   
174      134         391  248            23        102             18   
175     1327         428  226            20        120            159   
176     1317         259  237            20        120            165   
177     1413          41  274           245         96            205   

     Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity  Hue  \
0           306                    28              229              564  104   
1           276                    26              128              438  105   
2           324                     3              281              568  103   
3           349                    24              218               78   86   
4           269                    39              182              432  104   
..          ...                   ...              ...              ...  ...   
173          61                    52              106               77   64   
174          75                    43              141               73    7   
175          69                    43              135              102   59   
176          68                    53              146               93    6   
177          76                    56              135               92   61   

     OD280  Proline  Customer_Segment  
0      392     1065                 1  
1       34     1050                 1  
2      317     1185                 1  
3      345     1480                 1  
4      293      735                 1  
..     ...      ...               ...  
173    174      740                 3  
174    156      750                 3  
175    156      835                 3  
176    162      840                 3  
177     16      560                 3  

[178 rows x 14 columns]

In [4]:
#Öğrenilecek kolonları ve sonuç kolonlarını ayırıyoruz
X=Data1.iloc[:,0:13].values
Y=Data1.iloc[:,13].values

In [5]:
#Veriyi train ve test verisi olarak ayırıyoruz.
from sklearn.model_selection import train_test_split

In [6]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [7]:
#Verileri 0 ile 1 arasında skale ediyoruz
from sklearn.preprocessing import StandardScaler

In [8]:
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.fit_transform(x_test)

In [9]:
#PCA Principal Compent Analysis (Birincil Bileşen Analizi)
from sklearn.decomposition import PCA

In [10]:

pca=PCA(n_components=8)
X_train4=pca.fit_transform(X_train)
X_test4=pca.transform(X_test)

In [11]:
#İndirgenen veriyi Linear Fonksiyona öğretiyoruz.
from sklearn.linear_model import LogisticRegression

In [12]:
LR=LogisticRegression(random_state=0)
LR.fit(X_train4,y_train)
Y_pred4=LR.predict(X_test4)

In [13]:
LR2=LogisticRegression(random_state=0)
LR2.fit(X_train,y_train)
Y_pred=LR2.predict(X_test)

In [14]:
#Confusion Matrix ile test ediyoruz
from sklearn.metrics import confusion_matrix

In [15]:
print("PCA Lİ OLAN")
cm=confusion_matrix(Y_pred4,y_test)
print(cm)

PCA Lİ OLAN
[[ 8  0  0]
 [ 4 14  0]
 [ 2  2  6]]


In [16]:
print("PCA SİZ OLAN")
cm=confusion_matrix(Y_pred,y_test)
print(cm)

PCA SİZ OLAN
[[10  1  0]
 [ 2 15  0]
 [ 2  0  6]]


In [17]:
#KNN Modelini deniyoruz
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=7,metric="minkowski")
kn.fit(X_train,y_train)
KNtahmin=kn.predict(X_test)

In [18]:
cm=confusion_matrix(KNtahmin,y_test)

In [19]:
#SVC Modelini deniyoruz
from sklearn.svm import SVC
svc=SVC(kernel="linear")
svc.fit(X_train,y_train)
Tahmin=svc.predict(X_test)

In [20]:
cm=confusion_matrix(Tahmin,y_test)
cm

array([[10,  1,  0],
       [ 3, 13,  0],
       [ 1,  2,  6]], dtype=int64)

In [21]:
#Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(X_train,y_train)
Tahmin=nb.predict(X_test)
confusion_matrix(Tahmin,y_test)

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [14, 16,  6]], dtype=int64)

In [22]:
#Tree (Karar ağacı)
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(criterion="entropy")
dtc.fit(X_train,y_train)
Tahmin=dtc.predict(X_test)
confusion_matrix(y_test,Tahmin)

array([[10,  3,  1],
       [ 0, 16,  0],
       [ 0,  2,  4]], dtype=int64)

In [23]:
#Random forest (Rassal oraman)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=73,criterion="entropy")
rfc.fit(X_train,y_train)
Tahmin=rfc.predict(X_test)
confusion_matrix(y_test,Tahmin)

array([[12,  2,  0],
       [ 0, 16,  0],
       [ 0,  0,  6]], dtype=int64)

In [24]:

rfc2=RandomForestClassifier(n_estimators=73,criterion="entropy")
rfc2.fit(X_train4,y_train)
Tahmin=rfc2.predict(X_test4)
confusion_matrix(y_test,Tahmin)

array([[10,  2,  2],
       [ 1, 13,  2],
       [ 0,  0,  6]], dtype=int64)

In [25]:
#LDA linear Discriment Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [31]:
lda=LinearDiscriminantAnalysis(n_components=2)
X_lda_train=lda.fit_transform(X_train,y_train)
X_lda_test=lda.transform(X_test)

In [35]:
#LDA ile indirgenmiş Verilerini Modelerle deniyoruz.
#Random Forest(Rassal Orman)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=73,criterion="entropy")
rfc.fit(X_train,y_train)
Tahmin=rfc.predict(X_test)
confusion_matrix(y_test,Tahmin)

array([[13,  1,  0],
       [ 0, 16,  0],
       [ 0,  0,  6]], dtype=int64)

In [34]:
#Logistic versiyon
LR=LogisticRegression(random_state=0)
LR.fit(X_train4,y_train)
Y_pred4=LR.predict(X_test4)
confusion_matrix(y_test,Y_pred4)

array([[ 8,  4,  2],
       [ 0, 14,  2],
       [ 0,  0,  6]], dtype=int64)