In [11]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#2.veri onisleme
#2.1.veri yukleme
veriler = pd.read_csv('veriler.csv',delimiter=";")
veriler.drop([22],axis=0,inplace=True)
#pd.read_csv("veriler.csv")
#test
print(veriler)
Yas = veriler.iloc[:,1:4].values
print(Yas)

#encoder: Kategorik -> Numeric

ulke = veriler.iloc[:,0:1].values
print(ulke)

from sklearn import preprocessing

le = preprocessing.LabelEncoder()

ulke[:,0] = le.fit_transform(veriler.iloc[:,0])

print(ulke)

ohe = preprocessing.OneHotEncoder()
ulke = ohe.fit_transform(ulke).toarray()
print(ulke)

#encoder: Kategorik -> Numeric
c = veriler.iloc[:,-1:].values
print(c)



#verilerin egitim ve test icin bolunmesi








   ulke    boy   kilo   yas cinsiyet
0    tr  130.0   30.0  10.0        e
1    tr  125.0   36.0  11.0        e
2    tr  135.0   34.0  10.0        k
3    tr  133.0   30.0   9.0        k
4    tr  180.0   38.0  12.0        e
5    tr  190.0   90.0  30.0        e
6    tr  175.0   80.0  25.0        e
7    tr  177.0   90.0  35.0        e
8    tr  185.0   60.0  22.0        k
9    us  165.0  105.0  33.0        e
10   us  155.0   55.0  27.0        k
11   us  160.0   50.0  44.0        k
12   us  162.0   58.0  39.0        k
13   us  167.0   59.0  41.0        k
14   us  174.0   62.0  55.0        k
15   fr  193.0   70.0  47.0        e
16   fr  187.0   90.0  28.0        e
17   fr  183.0   80.0  29.0        e
18   fr  159.0   88.0  32.0        e
19   fr  164.0   40.0  42.0        k
20   fr  166.0   66.0  51.0        k
21   fr  166.0   56.0  62.0        k
[[130.  30.  10.]
 [125.  36.  11.]
 [135.  34.  10.]
 [133.  30.   9.]
 [180.  38.  12.]
 [190.  90.  30.]
 [175.  80.  25.]
 [177.  90.  35.]
 [185

In [12]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

c[:,-1] = le.fit_transform(veriler.iloc[:,-1])

print(c)


#numpy dizileri dataframe donusumu
sonuc = pd.DataFrame(data=ulke, index = range(22), columns = ["fr","tr","us"])
print(sonuc)

sonuc2 = pd.DataFrame(data=Yas, index = range(22), columns = ["boy","kilo","yas"])
print(sonuc2)

cinsiyet = veriler.iloc[:,-1].values
print(cinsiyet)

sonuc3 = pd.DataFrame(data = c[:,:1], index = range(22), columns = ["cinsiyet"])
print(sonuc3)


#dataframe birlestirme islemi
s=pd.concat([sonuc,sonuc2], axis=1)
print(s)

s2=pd.concat([s,sonuc3], axis=1)
print(s2)


[[0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]]
     fr   tr   us
0   0.0  1.0  0.0
1   0.0  1.0  0.0
2   0.0  1.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   0.0  1.0  0.0
7   0.0  1.0  0.0
8   0.0  1.0  0.0
9   0.0  0.0  1.0
10  0.0  0.0  1.0
11  0.0  0.0  1.0
12  0.0  0.0  1.0
13  0.0  0.0  1.0
14  0.0  0.0  1.0
15  1.0  0.0  0.0
16  1.0  0.0  0.0
17  1.0  0.0  0.0
18  1.0  0.0  0.0
19  1.0  0.0  0.0
20  1.0  0.0  0.0
21  1.0  0.0  0.0
      boy   kilo   yas
0   130.0   30.0  10.0
1   125.0   36.0  11.0
2   135.0   34.0  10.0
3   133.0   30.0   9.0
4   180.0   38.0  12.0
5   190.0   90.0  30.0
6   175.0   80.0  25.0
7   177.0   90.0  35.0
8   185.0   60.0  22.0
9   165.0  105.0  33.0
10  155.0   55.0  27.0
11  160.0   50.0  44.0
12  162.0   58.0  39.0
13  167.0   59.0  41.0
14  174.0   62.0  55.0
15  193.0   70.0  47.0
16  187.0   90.0  28.0
17  183.0   80.0  29.0
18  159.0   88.0  32.0
19  164.0   40.

fr   tr   us    boy   kilo   yas cinsiyet
0   0.0  1.0  0.0  130.0   30.0  10.0        0
1   0.0  1.0  0.0  125.0   36.0  11.0        0
2   0.0  1.0  0.0  135.0   34.0  10.0        1
3   0.0  1.0  0.0  133.0   30.0   9.0        1
4   0.0  1.0  0.0  180.0   38.0  12.0        0
5   0.0  1.0  0.0  190.0   90.0  30.0        0
6   0.0  1.0  0.0  175.0   80.0  25.0        0
7   0.0  1.0  0.0  177.0   90.0  35.0        0
8   0.0  1.0  0.0  185.0   60.0  22.0        1
9   0.0  0.0  1.0  165.0  105.0  33.0        0
10  0.0  0.0  1.0  155.0   55.0  27.0        1
11  0.0  0.0  1.0  160.0   50.0  44.0        1
12  0.0  0.0  1.0  162.0   58.0  39.0        1
13  0.0  0.0  1.0  167.0   59.0  41.0        1
14  0.0  0.0  1.0  174.0   62.0  55.0        1
15  1.0  0.0  0.0  193.0   70.0  47.0        0
16  1.0  0.0  0.0  187.0   90.0  28.0        0
17  1.0  0.0  0.0  183.0   80.0  29.0        0
18  1.0  0.0  0.0  159.0   88.0  32.0        0
19  1.0  0.0  0.0  164.0   40.0  42.0        1
20  1.0  0.0  0.0  166.0   66.0  51.0        1
21  1.0  0.0  0.0  166.0   56.0  62.0        1

In [13]:
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(s,sonuc3,test_size=0.33, random_state=0)


from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)

boy = s2.iloc[:,3:4].values
print(boy)
sol = s2.iloc[:,:3]
sag = s2.iloc[:,4:]

veri = pd.concat([sol,sag],axis=1)

x_train, x_test,y_train,y_test = train_test_split(veri,boy,test_size=0.33, random_state=0)


r2 = LinearRegression()
r2.fit(x_train,y_train)

y_pred = r2.predict(x_test)

[[130.]
 [125.]
 [135.]
 [133.]
 [180.]
 [190.]
 [175.]
 [177.]
 [185.]
 [165.]
 [155.]
 [160.]
 [162.]
 [167.]
 [174.]
 [193.]
 [187.]
 [183.]
 [159.]
 [164.]
 [166.]
 [166.]]


In [19]:
boy

array([[130.],
       [125.],
       [135.],
       [133.],
       [180.],
       [190.],
       [175.],
       [177.],
       [185.],
       [165.],
       [155.],
       [160.],
       [162.],
       [167.],
       [174.],
       [193.],
       [187.],
       [183.],
       [159.],
       [164.],
       [166.],
       [166.]])

In [14]:
import statsmodels.api as sm

X = np.append(arr = np.ones((22,1)).astype(int), values=veri, axis=1)

X_l = veri.iloc[:,[0,1,2,3,4,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
print(model.summary())


X_l = veri.iloc[:,[0,1,2,3,5]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
print(model.summary())



X_l = veri.iloc[:,[0,1,2,3]].values
X_l = np.array(X_l,dtype=float)
model = sm.OLS(boy,X_l).fit()
print(model.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.530
Model:                            OLS   Adj. R-squared:                  0.383
Method:                 Least Squares   F-statistic:                     3.612
Date:                Sat, 29 Jan 2022   Prob (F-statistic):             0.0223
Time:                        21:02:29   Log-Likelihood:                -87.891
No. Observations:                  22   AIC:                             187.8
Df Residuals:                      16   BIC:                             194.3
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1           117.5895     18.998      6.189      0.0